ADD: BEND-52 Field features to models sprint2
Worksut/user-microservice-api pull request #57
Opened 2022-02-03 10:14 UTC by octapf

2022-02-03 11:25 UTC, PatyVilas submitted a review, later dismissed

2022-02-03 11:25 UTC, octapf commented
@whitehatdevv please review

2022-02-03 13:09 UTC, whitehatdevv requested changes

2022-02-03 13:09 UTC, whitehatdevv commented on src/models/models.user.ts
> +  },
It's not needed a validator here, obiusly a boolean can only have true/false cases.

2022-02-03 13:09 UTC, whitehatdevv commented
Also @PatyVilas where is the REGEX to validate the new fields?

2022-02-03 13:46 UTC, octapf commented on src/models/models.user.ts
> +  },
Ok i will erase it

2022-02-04 10:57 UTC, PatyVilas submitted a review, later dismissed

2022-02-04 11:03 UTC, Kehomaxd approved these changes

2022-02-04 11:04 UTC, davidcode10 approved these changes
approved

2022-02-04 11:04 UTC, PatyVilas approved these changes

2022-02-04 11:29 UTC, OvidioSantoro approved these changes

2022-02-04 15:08 UTC, merged