FEATURE: BEND-56 Configure debugger
Worksut/user-microservice-api pull request #68
Opened 2022-02-08 12:10 UTC by octapf

Configure the internal debugger inside each controller, action, router.

- Import Debugger, DebuggerEnviroments and DebuggerTypes on routes, controllers and actions.
- Implement first Debugger Log on one endpoint

2022-02-09 06:55 UTC, whitehatdevv requested changes

2022-02-09 06:55 UTC, whitehatdevv commented on src/http/actions/User.ts
> +      `GetProfileAction`
What is that??????

2022-02-09 06:55 UTC, whitehatdevv commented on src/http/actions/User.ts
> +      `GetProfileAction`
The debugger should print:  
```
`Action GetProfileAction with an userId ${userId}`
```

2022-02-09 06:55 UTC, whitehatdevv commented on src/http/controller/User.ts
> +      'GetProfile Controller'
Same as before, the debug message must be explained, please don't copy the hard name of the controller

2022-02-09 07:07 UTC, octapf commented
@whitehatdevv i will fix this now.. i left you a comment yesterday saying i'm not sure what to put on the debug log

2022-02-09 07:17 UTC, whitehatdevv commented
> @whitehatdevv i will fix this now.. i left you a comment yesterday saying i'm not sure what to put on the debug log

Where is the comment?

2022-02-14 10:56 UTC, Kehomaxd submitted a review, later dismissed

2022-02-14 11:00 UTC, whitehatdevv requested changes
Pls delete all the comments 
`Call to debugger`

It's really clear

2022-02-14 13:08 UTC, PatyVilas approved these changes

2022-02-14 13:22 UTC, Kehomaxd approved these changes

2022-02-14 14:11 UTC, merged