FIX: BEND-71 Segmentation route controller and action code
Worksut/user-microservice-api pull request #75
Opened 2022-02-10 10:09 UTC by Kehomaxd

2022-02-10 14:32 UTC, OvidioSantoro submitted a review, later dismissed
I think everything's ok!

2022-02-10 14:32 UTC, davidcode10 submitted a review, later dismissed
Approved

2022-02-11 09:15 UTC, octapf requested changes

2022-02-11 09:15 UTC, octapf commented on src/http/controller/User.languages.ts
> + * !segmentation languages controller
@Kehomaxd spaces and capital letter missing

2022-02-11 09:15 UTC, octapf commented on src/http/controller/User.photos.ts
> + * !segmentation routes controller and actions code
@davidcode10 change this description so matches the others

2022-02-11 09:15 UTC, octapf commented on src/http/controller/User.photos.ts
> +export module UserControllerPhotos {
@davidcode10 Should be UserPhotosController

2022-02-11 09:15 UTC, octapf commented on src/routes/User.educations.ts
> + * !segmentation education routes
@Kehomaxd change file name and this description to singular

2022-02-11 09:51 UTC, OvidioSantoro approved these changes

2022-02-11 09:52 UTC, octapf approved these changes

2022-02-11 09:54 UTC, PatyVilas approved these changes

2022-02-11 09:55 UTC, davidcode10 approved these changes

2022-02-11 12:21 UTC, merged