FEATURE: BEND-62 Onboarding endpoint
Worksut/user-microservice-api pull request #76
Opened 2022-02-14 10:17 UTC by Kehomaxd

- add mobility in current situation
- add current situation in "me" interface

2022-02-14 14:41 UTC, davidcode10 approved these changes

2022-02-14 14:46 UTC, PatyVilas submitted a review, later dismissed

2022-02-14 15:30 UTC, OvidioSantoro approved these changes

2022-02-15 08:36 UTC, octapf requested changes

2022-02-15 08:36 UTC, octapf commented on src/http/actions/Auth.ts
> +      profilePhoto: dto.photo,
dto.photos should be plural > photos , because it's an array

2022-02-15 08:36 UTC, octapf commented on src/http/controller/Auth.ts
> +    const dto = OnBoardingDTOManager.CreateOnBoardingDTOManager(req.body);
call this const > onBoadingDTO

2022-02-15 08:36 UTC, octapf commented on src/models/model.currentSituation.ts
> +      values: ['Yes', 'No'],
change to boolean

2022-02-15 08:36 UTC, octapf commented on src/models/types/gen/dto/dto.onboarding.ts
> +  photo: Photo;
change name field to photos and change type to Photo[]

2022-02-15 10:42 UTC, OvidioSantoro submitted a review, later dismissed

2022-02-15 11:11 UTC, PatyVilas approved these changes

2022-02-15 11:15 UTC, davidcode10 approved these changes

2022-02-15 11:20 UTC, octapf commented on src/models/model.currentSituation.ts
> +      values: [true, false],
remove the enum. Look at the selftaught case:

selfTaught: {
    type: Boolean,
    required: true,
    validate: {
      validator: function (): Boolean {
        return true;
      },
      message: props => `${props.value} is not a valid option`,
    },
  },

2022-02-15 12:09 UTC, PatyVilas approved these changes

2022-02-15 12:09 UTC, OvidioSantoro approved these changes

2022-02-17 07:31 UTC, octapf approved these changes

2022-02-17 07:32 UTC, PatyVilas approved these changes

2022-02-17 08:47 UTC, merged