FEATURE: BEND-39 Ip locator package
Worksut/user-microservice-api pull request #80
Opened 2022-02-22 08:51 UTC by Kehomaxd

Implement ip locator

2022-02-22 13:18 UTC, whitehatdevv requested changes

2022-02-22 13:18 UTC, whitehatdevv commented on src/http/middleware/middleware.geoIp.ts
> +    req.user.userIpInfo = {
That's impossible if you haven't changed the global object of express.

2022-02-22 13:23 UTC, OvidioSantoro commented on src/http/middleware/middleware.geoIp.ts
> +    req.user.userIpInfo = {
@whitehatdevv,  we added it into the `TokenInternalInfo` model that is passed to the User as an optional parameter. So it's inside the global object User that is already declared in Express.

2022-02-22 13:24 UTC, OvidioSantoro commented on src/models/types/gen/gen.token.ts
> +  userIpInfo?: GeoIpLocation;
@whitehatdevv, here is where we added it.

2022-02-22 18:38 UTC, OvidioSantoro commented on src/http/middleware/middleware.geoIp.ts
> +//TODO how will our server update the IP DB regularly? (geoip-lite method > updatedb)
@whitehatdevv: We have to think how to implement the Geolocation database update and how often. We should do it regularly but it takes some time (between 10 and 20 minutes depending on your machine as we have tested). Maybe once a weekend? More often?

2022-02-22 18:42 UTC, Kehomaxd commented on src/http/actions/Auth.ts
> +            //TODO ask manu
@whitehatdevv  I'm not sure where and how to implement the geoIpLocation middleware in the actions and I'm not sure what this if else does

2022-02-22 18:44 UTC, OvidioSantoro commented on src/models/domain/domain.geoIpLocation.ts
> +  ll: Location;
@whitehatdevv: An "issue" here. As far as we have seen, the `Login` model doesn't ask for any of these two parameters and they might be legacy requirements, as the ticket is quite old (from before implementing half the database). Should we change the `Login` model or dismiss these requirements?

2022-02-22 18:57 UTC, OvidioSantoro commented on src/models/domain/domain.geoIpLocation.ts
> +  ll: Location;
Additionally, the `Works` model has a `Latitude` and `Longitude` elements (the equivalent to the ''ll" here). Maybe this was meant for the `Works` model and not `Login`?

2022-02-22 19:04 UTC, OvidioSantoro commented on src/http/actions/Auth.ts
> +            //TODO ask manu
Indeed. We would need a FindOneAndUpdate linked the the success of the Login process, but we're not sure where it should be placed and if we should use the `username` as filtering data for the query or if this `dto._id` is the user id. (I'm not sure either what this line do)

2022-02-24 09:26 UTC, OvidioSantoro approved these changes

2022-02-24 09:27 UTC, davidcode10 approved these changes

2022-02-24 09:27 UTC, octapf approved these changes

2022-02-24 09:34 UTC, PatyVilas approved these changes

2022-02-24 10:49 UTC, merged